version: "3.6"

services:

  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: casbin_rs
      MONGO_INITDB_ROOT_PASSWORD: casbin_rs

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: casbin_rs
      ME_CONFIG_MONGODB_ADMINPASSWORD: casbin_rs
